import{useEffect,useMemo,useState}from"react";
import{Check,ChevronRight,Clock,Package,UserRound,History,LogIn,RefreshCw,MapPin,LogOut}from"lucide-react";
import{supabase}from"./lib/supabase";
import{SessionWorker,Task,PickerProfile}from"./types";

type Tab="picks"|"history"|"profile";

export default function App(){
 const[profile,setProfile]=useState<PickerProfile|null>(null);
 const[worker,setWorker]=useState<SessionWorker|null>(null);
 const[tasks,setTasks]=useState<Task[]>([]);
 const[laneName,setLaneName]=useState<string|null>(null);
 const[tab,setTab]=useState<Tab>("picks");
 const[loading,setLoading]=useState(true);
 const[error,setError]=useState<string|null>(null);
 const[loginId,setLoginId]=useState(""); const[email,setEmail]=useState(""); const[password,setPassword]=useState(""); const[signingIn,setSigningIn]=useState(false);

 const load=async()=>{
  setError(null);
  const{data:{user}}=await supabase.auth.getUser();
  if(!user){setProfile(null);setWorker(null);setTasks([]);setLaneName(null);setLoading(false);return;}
  let{data:p,error:pe}=await supabase.from("picker_profiles").select("id,auth_user_id,picker_login_id,email,full_name,phone,city,locality,pincode,latitude,longitude,availability_status,application_status").eq("auth_user_id",user.id).maybeSingle();
  if(pe)throw pe;
  if(!p){
   await supabase.auth.signOut();
   setProfile(null);
   setWorker(null);
   setTasks([]);
   setLaneName(null);
   setLoading(false);
   return;
  }
  const currentProfile:PickerProfile={id:p.id,authUserId:p.auth_user_id,pickerLoginId:p.picker_login_id||"",email:p.email||user.email||"",fullName:p.full_name,phone:p.phone,city:p.city,locality:p.locality,pincode:p.pincode,latitude:p.latitude,longitude:p.longitude,availabilityStatus:p.availability_status,applicationStatus:p.application_status};
  setProfile(currentProfile);
  const{data:w,error:we}=await supabase.from("vendor_workers").select("id,vendor_id,auth_user_id,worker_name").eq("auth_user_id",user.id).eq("status","active").maybeSingle();
  if(we)throw we;
  if(w){
   const current:SessionWorker={id:w.id,vendorId:w.vendor_id,authUserId:w.auth_user_id,name:w.worker_name};setWorker(current);
   const{data:rows,error:te}=await supabase.from("order_item_picking_tasks").select("id,order_item_id,worker_id,quantity,status,assigned_at,picked_at,vendor_id,basket_id").eq("vendor_id",w.vendor_id).eq("status","assigned").order("assigned_at",{ascending:false});
   if(te)throw te;
   const{data:myPickedRows,error:myPickedError}=await supabase.from("order_item_picking_tasks").select("id,order_item_id,worker_id,quantity,status,assigned_at,picked_at,vendor_id,basket_id").eq("vendor_id",w.vendor_id).eq("status","picked").eq("worker_id",w.id).order("picked_at",{ascending:false});
   if(myPickedError)throw myPickedError;
   const allRows=[...(rows||[]),...(myPickedRows||[])];
   const itemIds=allRows.map((row:any)=>row.order_item_id).filter(Boolean);
   const{data:itemRows,error:itemError}=itemIds.length?await supabase.from("order_items").select("id,product_id,product_name,order_id").in("id",itemIds):{data:[],error:null};
   if(itemError)throw itemError;
   const orderIds=(itemRows||[]).map((row:any)=>row.order_id).filter(Boolean);
   const{data:orderRows,error:orderError}=orderIds.length?await supabase.from("orders").select("id,order_number").in("id",orderIds):{data:[],error:null};
   if(orderError)throw orderError;
   const itemById=new Map<string,any>();(itemRows||[]).forEach((row:any)=>itemById.set(row.id,row));
   const orderById=new Map<string,any>();(orderRows||[]).forEach((row:any)=>orderById.set(row.id,row));
   const productIds=(itemRows||[]).map((row:any)=>row.product_id).filter(Boolean);
   const{data:locs}=productIds.length?await supabase.from("product_storage_locations").select("product_id,vendor_lanes(lane_name),vendor_racks(rack_name)").in("product_id",productIds):{data:[]};
   const locationByProduct=new Map<string,any>();(locs||[]).forEach((x:any)=>locationByProduct.set(x.product_id,x));
   const basketIds=allRows.map((row:any)=>row.basket_id).filter(Boolean);
   const{data:baskets}=basketIds.length?await supabase.from("picker_baskets").select("id,basket_code,status").in("id",basketIds):{data:[]};
   const basketById=new Map<string,any>();(baskets||[]).forEach((x:any)=>basketById.set(x.id,x));
   setTasks(allRows.map((row:any)=>{const item=itemById.get(row.order_item_id);const order=item?orderById.get(item.order_id):null;const loc=locationByProduct.get(item?.product_id);const basket=row.basket_id?basketById.get(row.basket_id):null;return{id:row.id,orderItemId:row.order_item_id,workerId:row.worker_id||w.id,orderNumber:order?.order_number||"—",productName:item?.product_name||"Product Item",productId:item?.product_id||"",laneName:loc?.vendor_lanes?.lane_name||null,rackName:loc?.vendor_racks?.rack_name||null,basketId:row.basket_id||null,basketCode:basket?.basket_code||null,quantity:Number(row.quantity||0),status:row.status==="picked"?"picked":"assigned",assignedAt:row.assigned_at||"",completedAt:row.picked_at||""}}));const{data:laneAssignment}=await supabase.from("vendor_lane_picker_assignments").select("vendor_lanes(lane_name)").eq("worker_id",w.id).eq("status","active").maybeSingle();setLaneName((laneAssignment as any)?.vendor_lanes?.lane_name||null);
  }else{setWorker(null);setTasks([]);setLaneName(null);}

  setLoading(false);
 };

 useEffect(()=>{load().catch(e=>{console.error(e);setError(e.message||"Failed to load Picker.");setLoading(false)});const{data:{subscription}}=supabase.auth.onAuthStateChange(()=>load().catch(e=>setError(e.message||"Failed to refresh Picker.")));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!worker)return;const ch=supabase.channel("picker-tasks-"+worker.id).on("postgres_changes",{event:"*",schema:"public",table:"order_item_picking_tasks",filter:"vendor_id=eq."+worker.vendorId},(payload:any)=>{console.log("[Picker Realtime] order_item_picking_tasks",payload.eventType,payload.new?.id||payload.old?.id);load().catch(console.error)}).subscribe(status=>{if(status==="SUBSCRIBED")console.log("[Picker Realtime] task pool SUBSCRIBED");});return()=>{supabase.removeChannel(ch)}},[worker?.id,worker?.vendorId]);

 const myTasks=useMemo(()=>tasks.filter(t=>t.status==="assigned"),[tasks]);
 const history=useMemo(()=>tasks.filter(t=>t.status==="picked").sort((a,b)=>b.completedAt.localeCompare(a.completedAt)),[tasks]);
 const completedCount=history.reduce((n,t)=>n+t.quantity,0);
 const ordersWorked=new Set(tasks.map(t=>t.orderNumber)).size;

 async function markPicked(id:string){setError(null);if(!worker){setError("Picker worker is not active.");return}const now=new Date().toISOString();const{data:task,error:taskReadError}=await supabase.from("order_item_picking_tasks").select("id,worker_id,status").eq("id",id).eq("vendor_id",worker.vendorId).maybeSingle();if(taskReadError){setError(taskReadError.message);return}if(!task||task.status==="picked"){await load();return}const{data,error}=await supabase.from("order_item_picking_tasks").update({status:"picked",worker_id:worker.id,picked_at:now,updated_at:now}).eq("id",id).eq("vendor_id",worker.vendorId).neq("status","picked").select("id,status,worker_id,picked_at,updated_at").maybeSingle();if(error){setError(error.message);return}if(!data||data.status!=="picked"){await load();return}setTasks(v=>v.map(t=>t.id===id?{...t,workerId:worker.id,status:"picked",completedAt:data.picked_at||now}:t).filter(t=>t.id===id?true:t.status==="assigned"))}
 async function setAvailability(next:"available"|"offline"){if(!profile)return;const{error}=await supabase.from("picker_profiles").update({availability_status:next,updated_at:new Date().toISOString()}).eq("id",profile.id).eq("auth_user_id",profile.authUserId);if(error){setError(error.message);return}setProfile({...profile,availabilityStatus:next})}
 async function signIn(e:React.FormEvent){e.preventDefault();setSigningIn(true);setError(null);if(!/^Rpicker-[0-9]{4}$/.test(loginId.trim())||password.length<1||password.length>4){setError("Enter a valid Picker ID and a password of maximum 4 characters.");setSigningIn(false);return}const{data:pickerEmail,error:pickerError}=await supabase.rpc("get_picker_login_email",{p_picker_login_id:loginId.trim()});if(pickerError||!pickerEmail){setError("Picker ID not found.");setSigningIn(false);return}const{error}=await supabase.auth.signInWithPassword({email:pickerEmail,password:"Rivo@"+password});if(error){setError(error.message||"Unable to sign in.");setSigningIn(false);return}setSigningIn(false)}
 async function signOut(){await supabase.auth.signOut();setProfile(null);setWorker(null);setTasks([])}

 if(loading)return <div className="min-h-screen bg-slate-50 flex items-center justify-center text-sm font-bold text-slate-500">Loading RivoCity Picker…</div>;
 if(!profile)return <RegisterOrLogin loginId={loginId} email={email} password={password} setLoginId={setLoginId} setEmail={setEmail} setPassword={setPassword} onSignIn={signIn} signingIn={signingIn} error={error}/>;

 const applicationPending=profile.applicationStatus!=="approved";
 return <div className="min-h-screen bg-slate-50 text-slate-900">
  <header className="sticky top-0 z-20 bg-white border-b"><div className="max-w-xl mx-auto px-4 h-16 flex items-center justify-between"><div><div className="font-black text-xl tracking-tight">RivoCity <span className="text-emerald-600">Picker</span></div><div className="text-[10px] text-slate-400 font-bold tracking-widest">WORKER PWA</div></div><div className="w-9 h-9 rounded-full bg-emerald-50 text-emerald-700 flex items-center justify-center"><UserRound size={18}/></div></div></header>
  <main className="max-w-xl mx-auto px-4 py-5 pb-24">
   {error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
   {applicationPending?<ApplicationState profile={profile} onAvailability={setAvailability}/>:<>
    {tab==="picks"&&<Picks worker={worker} tasks={myTasks} laneName={laneName} onPick={markPicked}/>}
    {tab==="history"&&<HistoryView tasks={history} completedCount={completedCount}/>}
    {tab==="profile"&&<Profile profile={profile} worker={worker} itemsPicked={completedCount} ordersWorked={ordersWorked} onAvailability={setAvailability} onRefresh={()=>load().catch(e=>setError(e.message||"Refresh failed."))} onSignOut={signOut}/>}
   </>}
  </main>
  {!applicationPending&&<nav className="fixed bottom-0 inset-x-0 bg-white border-t"><div className="max-w-xl mx-auto grid grid-cols-4 h-16">
   <NavButton active={tab==="picks"} icon={<Package size={18}/>} label="My Picks" onClick={()=>setTab("picks")}/>
   <NavButton active={tab==="history"} icon={<History size={18}/>} label="History" onClick={()=>setTab("history")}/>
   <NavButton active={tab==="profile"} icon={<UserRound size={18}/>} label="Profile" onClick={()=>setTab("profile")}/>
  </div></nav>}
 </div>
}

function RegisterOrLogin({loginId,email,password,setLoginId,setEmail,setPassword,onSignIn,signingIn,error}:{loginId:string;email:string;password:string;setLoginId:(v:string)=>void;setEmail:(v:string)=>void;setPassword:(v:string)=>void;onSignIn:(e:React.FormEvent)=>void;signingIn:boolean;error:string|null}){
 const[mode,setMode]=useState<"login"|"register">("login");const[name,setName]=useState("");const[phone,setPhone]=useState("");const[city,setCity]=useState("");const[locality,setLocality]=useState("");const[address,setAddress]=useState("");const[pincode,setPincode]=useState("");const[lat,setLat]=useState<number|null>(null);const[lng,setLng]=useState<number|null>(null);const[message,setMessage]=useState("");
 const register=async(e:React.FormEvent)=>{e.preventDefault();setMessage("");setErrorLocal("");if(!name||!phone||!city||!email||!password){setErrorLocal("Fill all required fields.");return}if(password.length>4){setErrorLocal("Password must be maximum 4 characters.");return}if(pincode&&!/^[0-9]{6}$/.test(pincode)){setErrorLocal("Pincode must be exactly 6 digits.");return}const{data,error}=await supabase.auth.signUp({email:email.trim().toLowerCase(),password:"Rivo@"+password,options:{data:{picker_role:"picker",registration_source:"pwa",full_name:name.trim(),phone:phone.trim(),city:city.trim(),locality:locality.trim()||null,address:address.trim()||null,pincode:pincode.trim()||null,latitude:lat,longitude:lng}}});if(error){if(error.status===422||/already registered|user already registered/i.test(error.message||"")){const existingEmail=email.trim().toLowerCase();const{data:existingPicker}=await supabase.from("picker_profiles").select("picker_login_id").eq("email",existingEmail).maybeSingle();setEmail(existingEmail);if(existingPicker?.picker_login_id)setLoginId(existingPicker.picker_login_id);setMode("login");setMessage(existingPicker?.picker_login_id?`This email is already registered. Your Picker ID is ${existingPicker.picker_login_id}. Sign in with that ID and your password.`:"This email is already registered. Switch to Sign In and use the existing Picker ID and password.");setErrorLocal("");return}setErrorLocal(error.message);return}const generatedId=data.user?.user_metadata?.picker_login_id||"assigned by Rivo";setMessage(data.session?"Registration submitted. Your Picker ID is "+generatedId+". Your profile is pending Admin approval.":"Registration submitted. Your Picker ID is "+generatedId+". Check your email to confirm your account, then wait for Admin approval.");};
 const[errorLocal,setErrorLocal]=useState("");
 const constloc=()=>navigator.geolocation?.getCurrentPosition(p=>{setLat(p.coords.latitude);setLng(p.coords.longitude);setMessage("Location captured for nearby vendor matching.")},()=>setErrorLocal("Location permission was not granted."));
 return <div className="min-h-screen bg-slate-50 flex items-center justify-center p-4"><form onSubmit={mode==="login"?onSignIn:register} className="w-full max-w-sm bg-white border rounded-2xl p-6 shadow-sm"><div className="font-black text-2xl">RivoCity <span className="text-emerald-600">Picker</span></div><p className="text-sm text-slate-500 mt-1">{mode==="login"?"Worker sign in":"Register as a Picker"}</p>{(error||errorLocal)&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700">{error||errorLocal}</div>}{message&&<div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-700">{message}</div>}
 {mode==="login"&&<label className="block text-xs font-bold text-slate-500 mt-5">Picker ID<input value={loginId} onChange={e=>setLoginId(e.target.value)} placeholder="Rpicker-1234" maxLength={12} className="mt-1 w-full border rounded-xl px-3 py-3"/></label>}{mode==="register"&&<><label className="block text-xs font-bold text-slate-500 mt-5">Full name<input value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full border rounded-xl px-3 py-3"/></label><label className="block text-xs font-bold text-slate-500 mt-3">Mobile number<input value={phone} onChange={e=>setPhone(e.target.value)} type="tel" className="mt-1 w-full border rounded-xl px-3 py-3"/></label><label className="block text-xs font-bold text-slate-500 mt-3">City<input value={city} onChange={e=>setCity(e.target.value)} className="mt-1 w-full border rounded-xl px-3 py-3"/></label><label className="block text-xs font-bold text-slate-500 mt-3">Area / locality<input value={locality} onChange={e=>setLocality(e.target.value)} className="mt-1 w-full border rounded-xl px-3 py-3"/></label><label className="block text-xs font-bold text-slate-500 mt-3">Address<input value={address} onChange={e=>setAddress(e.target.value)} className="mt-1 w-full border rounded-xl px-3 py-3"/></label><label className="block text-xs font-bold text-slate-500 mt-3">Pincode<input value={pincode} onChange={e=>setPincode(e.target.value.replace(/[^0-9]/g,"").slice(0,6))} maxLength={6} inputMode="numeric" className="mt-1 w-full border rounded-xl px-3 py-3"/></label><button type="button" onClick={constloc} className="mt-3 w-full border rounded-xl py-3 font-bold text-slate-600 flex items-center justify-center gap-2"><MapPin size={17}/>{lat?"Location captured":"Use current location"}</button></> }
 <label className={"block text-xs font-bold text-slate-500 mt-3 "+(mode==="login"?"hidden":"")}>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required={mode==="register"} disabled={mode==="login"} aria-hidden={mode==="login"} tabIndex={mode==="login"?-1:0} className="mt-1 w-full border rounded-xl px-3 py-3"/></label><label className="block text-xs font-bold text-slate-500 mt-3">{mode==="login"?"Password (max 4 characters)":"Password (max 4 characters)"}<input value={password} maxLength={4} onChange={e=>setPassword(e.target.value.slice(0,4))} type="password" required className="mt-1 w-full border rounded-xl px-3 py-3"/></label><button disabled={signingIn} className="mt-5 w-full bg-emerald-600 disabled:opacity-60 text-white rounded-xl py-3.5 font-black flex items-center justify-center gap-2">{mode==="login"?<><LogIn size={18}/>{signingIn?"Signing in…":"Sign In"}</>:"Submit Registration"}</button><button type="button" onClick={()=>{setMode(mode==="login"?"register":"login");setErrorLocal("");setMessage("")}} className="mt-3 w-full text-sm font-bold text-emerald-700">{mode==="login"?"New Picker? Register here":"Already registered? Sign in"}</button></form></div>
}

function ApplicationState({profile,onAvailability}:{profile:PickerProfile;onAvailability:(v:"available"|"offline")=>void}){return <section className="space-y-4"><div><p className="text-sm text-slate-500">Application status</p><h1 className="text-2xl font-black">{profile.applicationStatus==="pending"?"Waiting for approval":profile.applicationStatus==="rejected"?"Application not approved":"Picker access paused"}</h1></div><div className="bg-white border rounded-2xl p-5"><p className="text-sm text-slate-600">Your Picker profile is registered with RivoCity. An admin must approve it before vendors can request you.</p><div className="mt-4 text-sm font-bold text-slate-500">Location: {profile.city}{profile.locality?" · "+profile.locality:""}</div></div></section>}

function Picks({worker,tasks,laneName,onPick}:{worker:SessionWorker|null;tasks:Task[];laneName:string|null;onPick:(id:string)=>void}){return <section className="space-y-4"><div><p className="text-sm text-slate-500">Available Picks</p><h1 className="text-2xl font-black">{worker?.name||"RivoCity Picker"}</h1><p className="text-sm text-slate-500 mt-1">{tasks.length?tasks.length+" items available":"No items waiting to be picked."}</p><p className="text-xs text-slate-500 mt-1">Take one basket/cart and move through the store. Any active Picker can pick any available item; lane and rack are only location hints.</p>{laneName&&<p className="text-xs font-bold text-emerald-700 mt-1">Usual Lane: {laneName}</p>}</div>{tasks.map(task=><article key={task.id} className="bg-white border rounded-2xl p-4 shadow-sm"><div className="flex items-start justify-between"><div><div className="text-xs font-bold text-emerald-700 uppercase">Order {task.orderNumber}</div><h2 className="font-black text-lg mt-1">{task.productName}</h2><p className="text-sm text-slate-500 mt-1">Quantity: <b className="text-slate-900">{task.quantity}</b></p>{task.basketCode&&<p className="text-xs font-bold text-slate-600 mt-1">Order Basket: {task.basketCode}</p>}{task.laneName||task.rackName?<p className="text-xs font-bold text-emerald-700 mt-1">Location: {task.laneName||"Store"}{task.rackName?" → "+task.rackName:""}</p>:<p className="text-xs font-semibold text-slate-500 mt-1">No shelf location configured — pick directly from the store.</p>}<p className="text-xs text-slate-500 mt-1">Pick the item and mark it as picked. Another Picker cannot pick it after it is completed.</p></div><Clock size={18} className="text-slate-300"/></div><button onClick={()=>onPick(task.id)} className="mt-4 w-full bg-emerald-600 text-white rounded-xl py-3.5 font-black flex items-center justify-center gap-2">Mark Picked <ChevronRight size={18}/></button></article>)}</section>}

function HistoryView({tasks,completedCount}:{tasks:Task[];completedCount:number}){return <section className="space-y-4"><div><p className="text-sm text-slate-500">Your completed picks</p><h1 className="text-2xl font-black">History</h1></div><div className="bg-white border rounded-2xl p-4"><p className="text-xs text-slate-500">TOTAL ITEMS PICKED</p><p className="text-3xl font-black mt-1">{completedCount}</p></div>{tasks.length===0&&<div className="bg-white border rounded-xl p-6 text-center text-sm text-slate-500">No completed picks yet.</div>}{tasks.map(t=><div key={t.id} className="bg-white border rounded-xl p-4 flex justify-between"><div><div className="font-bold">{t.productName}</div><div className="text-xs text-slate-500">Order {t.orderNumber} · Qty {t.quantity}</div></div><Check size={19} className="text-emerald-600"/></div>)}</section>}

function Profile({profile,worker,itemsPicked,ordersWorked,onAvailability,onRefresh,onSignOut}:{profile:PickerProfile;worker:SessionWorker|null;itemsPicked:number;ordersWorked:number;onAvailability:(v:"available"|"offline")=>void;onRefresh:()=>void;onSignOut:()=>void}){return <section className="space-y-4"><div><p className="text-sm text-slate-500">Picker profile</p><h1 className="text-2xl font-black">{profile.fullName}</h1><p className="text-xs font-black text-emerald-700 mt-1">{profile.pickerLoginId}</p><p className="text-xs text-slate-500 mt-1">{profile.email}</p><p className="text-sm text-slate-500">{profile.city}{profile.locality?" · "+profile.locality:""}</p></div><div className="bg-white border rounded-2xl p-5"><p className="text-xs font-bold text-slate-400 uppercase">Availability</p><div className="flex gap-2 mt-3"><button onClick={()=>onAvailability("available")} className={"flex-1 rounded-xl py-3 font-bold "+(profile.availabilityStatus==="available"?"bg-emerald-600 text-white":"border")}>Available</button><button onClick={()=>onAvailability("offline")} className={"flex-1 rounded-xl py-3 font-bold "+(profile.availabilityStatus==="offline"?"bg-slate-900 text-white":"border")}>Offline</button></div></div><div className="bg-white border rounded-2xl p-5"><p className="text-xs font-bold text-slate-400 uppercase">Picking record</p><div className="grid grid-cols-2 gap-3 mt-4"><div className="bg-slate-50 rounded-xl p-4"><p className="text-xs text-slate-500">Items picked</p><p className="text-2xl font-black mt-1">{itemsPicked}</p></div><div className="bg-slate-50 rounded-xl p-4"><p className="text-xs text-slate-500">Orders worked</p><p className="text-2xl font-black mt-1">{ordersWorked}</p></div></div></div><button onClick={onRefresh} className="w-full border bg-white rounded-xl py-3 font-bold flex items-center justify-center gap-2"><RefreshCw size={17}/>Refresh</button><button onClick={onSignOut} className="w-full border bg-white rounded-xl py-3 font-bold text-red-600 flex items-center justify-center gap-2"><LogOut size={17}/>Sign Out</button></section>}

function NavButton({active,icon,label,badge,onClick}:{active:boolean;icon:React.ReactNode;label:string;badge?:number;onClick:()=>void}){return <button onClick={onClick} className={"relative flex flex-col items-center justify-center gap-1 text-xs font-bold "+(active?"text-emerald-700":"text-slate-400")}>{icon}<span>{label}</span>{badge? <span className="absolute top-1 right-5 min-w-4 h-4 px-1 rounded-full bg-red-500 text-white text-[9px] flex items-center justify-center">{badge}</span>:null}</button>}
